function _AcilirMenuOlustur(AKenarRenk, AGovdeRenk, ASecimRenk, ANormalYaziRenk,
  ASeciliYaziRenk: TRenk): TKimlik; assembler;
procedure _AcilirMenuGoster(AKimlik: TKimlik); assembler;
procedure _AcilirMenuGizle(AKimlik: TKimlik); assembler;
procedure _AcilirMenuElemanEkle(AKimlik: TKimlik; AElemanAdi: string; AResimSiraNo: TISayi4); assembler;
function _AcilirMenuSeciliSiraNoAl(AKimlik: TKimlik): TISayi4; assembler;
