function _GirisKutusuOlustur(AtaKimlik: TKimlik; A1, B1, AGenislik,
  AYukseklik: TISayi4; AIcerikDeger: string): TKimlik;
procedure _GirisKutusuGoster(AKimlik: TKimlik);
procedure _GirisKutusuIcerikAl(AKimlik: TKimlik; AHedefBellek: Isaretci);
procedure _GirisKutusuIcerikYaz(AKimlik: TKimlik; AIcerikDeger: string);
procedure _GirisKutusuYazilamaz0(AKimlik: TKimlik; AYazilamaz: LongBool);
procedure _GirisKutusuSadeceRakam0(AKimlik: TKimlik; ASadeceSayi: LongBool);
