function _KarmaListeOlustur(AtaKimlik: TKimlik; A1, B1, AGenislik,
  AYukseklik: TISayi4): TKimlik; assembler;
procedure _KarmaListeHizala(AKimlik: TKimlik; AHiza: THiza); assembler;
procedure _KarmaListeElemanEkle(AKimlik: TKimlik; AElemanAdi: string); assembler;
procedure _KarmaListeTemizle(AKimlik: TKimlik); assembler;
procedure _KarmaListeSeciliYaziAl(AKimlik: TKimlik; AHedefBellek: Isaretci); assembler;
