procedure _HarfYaz(AKimlik: TKimlik; A1, B1: TISayi4; ARenk: TRenk; AKarakter: Char);
procedure _YaziYaz(AKimlik: TKimlik; A1, B1: TISayi4; ARenk: TRenk; ADeger: string);
procedure _SayiYaz10(AKimlik: TKimlik; A1, B1: TISayi4; ARenk: TRenk; ADeger: TISayi4);
procedure _SayiYaz16(AKimlik: TKimlik; A1, B1: TISayi4; ARenk: TRenk; AOnekYaz: LongBool;
  AHaneSayisi: TSayi4; ADeger: TISayi4);
procedure _SaatYaz(AKimlik: TKimlik; A1, B1: TISayi4; ARenk: TRenk; ASaat: TSaat);
procedure _MACAdresiYaz(AKimlik: TKimlik; A1, B1: TISayi4; ARenk: TRenk; AMACAdres: PMACAdres);
procedure _IPAdresiYaz(AKimlik: TKimlik; A1, B1: TISayi4; ARenk: TRenk; AIPAdres: PIPAdres);
