function ToplamPCIAygitSayisiAl: TISayi4;
procedure PCIAygitBilgisiAl(AAygitSiraNo: TSayi4; ABellek: Isaretci);
function PCIOku1(AYol, AAygit, AIslev, ASiraNo: TSayi4): TSayi1;
function PCIOku2(AYol, AAygit, AIslev, ASiraNo: TSayi4): TSayi2;
function PCIOku4(AYol, AAygit, AIslev, ASiraNo: TSayi4): TSayi4;
procedure PCIYaz1(AYol, AAygit, AIslev, ASiraNo: TSayi4; ADeger: TSayi1);
procedure PCIYaz2(AYol, AAygit, AIslev, ASiraNo: TSayi4; ADeger: TSayi2);
procedure PCIYaz4(AYol, AAygit, AIslev, ASiraNo, ADeger: TSayi4);
